apiVersion: v1
kind: Service
metadata:
  name: {{ include "mcp-base.fullname" . }}
  labels:
    {{- include "mcp-base.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
{{- if .Values.testSidecar.enabled }}
    - port: {{ .Values.service.testPort }}
      targetPort: http-test
      protocol: TCP
      name: http-test
{{- end }}
  selector:
    {{- include "mcp-base.selectorLabels" . | nindent 4 }}
